plugins {
    id 'java'
}

group = 'org.irwan'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.seleniumhq.selenium:selenium-java:4.48.0'
    implementation("io.github.bonigarcia:webdrivermanager:6.3.4")

    implementation("io.cucumber:cucumber-java:7.34.7")
    testImplementation("io.cucumber:cucumber-junit:7.34.7")

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnit()
}

configurations {
    cucumberRuntime {
    extendsFrom testImplementation
    }
}

def tags = (findProperty('tags') == null) ? 'not @exclude' : findProperty('tags') + ' and not @exclude'

task cucumber(){
    description('Running Cucumber Test')
    dependsOn assemble, compileTestJava
    doLast {
        javaexec {
            main = "io.cucumber.core.cli.Main"
            classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
            args = [
                    '--plugin', 'html:report/test-report.html',
                    '--plugin', 'pretty',
                    '--glue', 'stepdef',
                    '--tags', "${tags}",
                    "src/test/resources"
            ]
        }
    }
}